//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer.EmployeesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesService.ICreateEmployeeService")]
    public interface ICreateEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/ICreateEmployeeService/CreateEmployeeResponse")]
        string CreateEmployee(EmployeeService.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/ICreateEmployeeService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<string> CreateEmployeeAsync(EmployeeService.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEmployeeService/AddRemarks", ReplyAction="http://tempuri.org/ICreateEmployeeService/AddRemarksResponse")]
        string AddRemarks(int id, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEmployeeService/AddRemarks", ReplyAction="http://tempuri.org/ICreateEmployeeService/AddRemarksResponse")]
        System.Threading.Tasks.Task<string> AddRemarksAsync(int id, string remarks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEmployeeServiceChannel : Consumer.EmployeesService.ICreateEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEmployeeServiceClient : System.ServiceModel.ClientBase<Consumer.EmployeesService.ICreateEmployeeService>, Consumer.EmployeesService.ICreateEmployeeService {
        
        public CreateEmployeeServiceClient() {
        }
        
        public CreateEmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateEmployee(EmployeeService.Employee e) {
            return base.Channel.CreateEmployee(e);
        }
        
        public System.Threading.Tasks.Task<string> CreateEmployeeAsync(EmployeeService.Employee e) {
            return base.Channel.CreateEmployeeAsync(e);
        }
        
        public string AddRemarks(int id, string remarks) {
            return base.Channel.AddRemarks(id, remarks);
        }
        
        public System.Threading.Tasks.Task<string> AddRemarksAsync(int id, string remarks) {
            return base.Channel.AddRemarksAsync(id, remarks);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesService.IRetrieveEmployeeService")]
    public interface IRetrieveEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/GetEmployeesResponse")]
        EmployeeService.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<EmployeeService.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/SearchById", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/SearchByIdResponse")]
        EmployeeService.Employee SearchById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/SearchById", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/SearchByIdResponse")]
        System.Threading.Tasks.Task<EmployeeService.Employee> SearchByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/SearchByName", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/SearchByNameResponse")]
        EmployeeService.Employee SearchByName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveEmployeeService/SearchByName", ReplyAction="http://tempuri.org/IRetrieveEmployeeService/SearchByNameResponse")]
        System.Threading.Tasks.Task<EmployeeService.Employee> SearchByNameAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetrieveEmployeeServiceChannel : Consumer.EmployeesService.IRetrieveEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveEmployeeServiceClient : System.ServiceModel.ClientBase<Consumer.EmployeesService.IRetrieveEmployeeService>, Consumer.EmployeesService.IRetrieveEmployeeService {
        
        public RetrieveEmployeeServiceClient() {
        }
        
        public RetrieveEmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrieveEmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveEmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveEmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeService.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<EmployeeService.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public EmployeeService.Employee SearchById(int Id) {
            return base.Channel.SearchById(Id);
        }
        
        public System.Threading.Tasks.Task<EmployeeService.Employee> SearchByIdAsync(int Id) {
            return base.Channel.SearchByIdAsync(Id);
        }
        
        public EmployeeService.Employee SearchByName(string Name) {
            return base.Channel.SearchByName(Name);
        }
        
        public System.Threading.Tasks.Task<EmployeeService.Employee> SearchByNameAsync(string Name) {
            return base.Channel.SearchByNameAsync(Name);
        }
    }
}
